language: scala
sudo: false
jdk:
  - oraclejdk8

scala:
  - 2.11.8
  - 2.12.3

script: sbt ++$TRAVIS_SCALA_VERSION clean coverageTest

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/
  - $HOME/.zinc

after_success: sbt ++$TRAVIS_SCALA_VERSION travis-report

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
